### PR TITLE
Add mean GVI to edge attributes

### PR DESCRIPTION
**Pull request by hellej**
- GVI point data: https://doi.org/10.1016/j.dib.2020.105601
- Land cover data: https://hri.fi/data/fi/dataset/paakaupunkiseudun-maanpeiteaineisto
- Similar approach as in https://github.com/EWillberg/Helsinki_GreenNetwork

Epic: DigitalGeographyLab/green-paths/issues/2

### CODE REVIEW

**Comment by hellej** [comment]
@EWillberg @apoom I am working on the GVI join now.

Elias, were you able to find a land cover layer that contains all vegetation higher than 2m? I could only find separate layers for 2-10m, 10-15m and so on from https://hri.fi/data/fi/dataset/paakaupunkiseudun-maanpeiteaineisto

Also, I am already thinking how to improve GVI prediction outside GVI point data. We could assess intersection with low and high vegetation (i.e. grass and trees) separately. So the share of high vegetation within buffered street geometry would contribute to street GVI more than the share of low vegetation (?). In any case, I think both should be used at least combined as GVI in parks would otherwise get badly underestimated (if only higher than 2m was used).

**Comment by EWillberg** [comment]
@hellej That's great to hear that you're working with it! :) Sorry for the slow reply.

For your first question, I simply created a composite of different available layers (2-10 m, 10-15 m etc.) with union and used that as the "greenery" layer.

For the second question, There are definitively many approaches that we could maybe try to "improve" the GVI. However, I also see that keeping the process simple is also an asset as we still don't have very good understanding on what GVI actually presents. Therefore we don't really know if we are actually "improving" the index. Because the impact of green exposure is not nearly as clear as for example the impact of noise where you have clear guidelines for high and low noise. Having e.g. 50% of greenery index will always be more arbitrary whether it's consisting of trees only or trees and grass and therefore the simpler approach to me might be better. Of course the things might change if in the future (e.g. GREENWAY) we'll get more understanding of the true/measured impacts of greenery exposure.

Another reason, why I wouldn't necessarily include the under 2m vegetation just yet, is the correlation with Google Street View images. As our purpose at this point is mainly to complement GSV-based index with land cover data and as we have found that over 2m vegetation has better correlation with the GSV-index than all vegetation, I would see that as one reason to only use over 2m vegetation even if that indeed neglects the parks. I'm not saying that GSV-index is necessarily the best approach to quantify urban greenery, but as long as we don't have any comparative research on the validity of different greenery index approaches, using GSV-index and complementing it with the most correlating data seems to me the best approach.

**Comment by hellej** [comment]
Thanks @EWillberg for sharing these well reasoned thoughts! Indeed, we should keep the index quite simple due to the many unknowns, at least for the research use. I'll probably include also the share of low vegetation as an additional (optional) index, that you can either use or omit when starting the route planner. 

The PostGIS approach was in the end the only viable way to do the overlay analysis, Python/GeoPandas were just too slow (I should not have even wasted time trying). So thanks for sharing the SQL scripts you used, they were really helpful! 

As for the online UI, I think I will calculate some kind of composite index from the point GVI, low vegetation and over 2m vegetation and use it there. Omitting low vegetation would likely confuse users too much, at least more than the (hidden) complexity of the composite index, as routes through parks could then be shown as "low in greenery" etc. Also, if we look at the classified image from [Toikka's study](https://blogs.helsinki.fi/digital-geography/2019/09/16/how-green-are-the-streets-of-helsinki/), low vegetation (grass) is classified just as green as any higher vegetation. So one could reason that the better correlation with over 2m vegetation and street view GVI has more to do with the presence of trees and smaller share of low vegetation in the images (rather than low vegetation possibly not correlating with GVI). But yes, all this is definitely something of which more knowledge needs to be acquired via future studies, as you said, and until then considered as mostly experimental.

Screen Shot 2020-12-14 at 8 25 33

**Comment by EWillberg** [comment]
@hellej Thanks for the response! It's a good idea to have one index with > 2m vegetation only and then an optional index with low vegetation + >2m vegetation. That way we can use the >2m vegetation index in the article, which is then similar than described in Toikka et al. (2020) data description article, but online UI can use the broader index. 

You're probably right that the correlation of low vegetation in Akseli's thesis was lower because street view images are seldom from parks. As for the broader index (low vegetation + >2m vegetation), I think some weighting still should be done even in the online tool as you also said earlier. Especially as the land cover data is polygon data, it might happen than you get 90% green index in parks like Arabianranta, which are still quite different environments compared to 90% green index derived from >2m vegetation areas  (e.g. Keskuspuisto). So maybe using some weight factor for the low vegetation to lower it's impact in the index, might be appropriate.

**Pull request merged**
